### PR TITLE
Revamp and update the snippets

### PR DESCRIPTION
**Pull request by SShrike**
I've added snippets for common language constructs such as if statements, for-in statements, `print()`, `class`, `struct`, `enum`, etc.

### CODE REVIEW

**Comment by mvdve** [comment]
Please merge this pull request. It would be nice to have better swift support. Thanks!

**Comment by SShrike** [comment]
This may as well be merged. It's in a working state, the only reason it was WIP is because I hadn't finished adding all of the snippets I wanted to it.

If I ever get around to adding the extra snippets I'll create new PR.

**Comment by freebroccolo** [comment]
Thanks!

**Comment by mvdve** [comment]
Great thanks! Can you also create a new version/tag when this is appropriate? Would be nice for the Atom users :-)

**Pull request merged**
